# coding: utf-8

"""
    TGS API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 6.4.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.chat_api import ChatApi  # noqa: E501
from swagger_client.rest import ApiException


class TestChatApi(unittest.TestCase):
    """ChatApi unit test stubs"""

    def setUp(self):
        self.api = api.chat_api.ChatApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_chat_controller_create(self):
        """Test case for chat_controller_create

        Create a new chat bot model.  # noqa: E501
        """
        pass

    def test_chat_controller_delete(self):
        """Test case for chat_controller_delete

        Delete a Tgstation.Server.Api.Models.ChatBot.  # noqa: E501
        """
        pass

    def test_chat_controller_get_id(self):
        """Test case for chat_controller_get_id

        Get a specific Tgstation.Server.Api.Models.ChatBot.  # noqa: E501
        """
        pass

    def test_chat_controller_list(self):
        """Test case for chat_controller_list

        List Tgstation.Server.Api.Models.ChatBots.  # noqa: E501
        """
        pass

    def test_chat_controller_update(self):
        """Test case for chat_controller_update

        Updates a chat bot model.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
