# coding: utf-8

"""
    TGS API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 6.4.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.configuration_file import ConfigurationFile  # noqa: E501
from swagger_client.rest import ApiException


class TestConfigurationFile(unittest.TestCase):
    """ConfigurationFile unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConfigurationFile(self):
        """Test ConfigurationFile"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.configuration_file.ConfigurationFile()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
