# coding: utf-8

"""
    TGS API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 6.4.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.test_merge import TestMerge  # noqa: E501
from swagger_client.rest import ApiException


class TestTestMerge(unittest.TestCase):
    """TestMerge unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTestMerge(self):
        """Test TestMerge"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.test_merge.TestMerge()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
