# coding: utf-8

"""
    TGS API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 6.4.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.instance_api import InstanceApi  # noqa: E501
from swagger_client.rest import ApiException


class TestInstanceApi(unittest.TestCase):
    """InstanceApi unit test stubs"""

    def setUp(self):
        self.api = api.instance_api.InstanceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_instance_controller_create(self):
        """Test case for instance_controller_create

        Create or attach an Tgstation.Server.Api.Models.Instance.  # noqa: E501
        """
        pass

    def test_instance_controller_delete(self):
        """Test case for instance_controller_delete

        Detach an Tgstation.Server.Api.Models.Instance with the given id.  # noqa: E501
        """
        pass

    def test_instance_controller_get_id(self):
        """Test case for instance_controller_get_id

        Get a specific Tgstation.Server.Api.Models.Instance.  # noqa: E501
        """
        pass

    def test_instance_controller_list(self):
        """Test case for instance_controller_list

        List Tgstation.Server.Api.Models.Instances.  # noqa: E501
        """
        pass

    def test_instance_controller_update(self):
        """Test case for instance_controller_update

        Modify an Tgstation.Server.Api.Models.Instance's settings.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
