# coding: utf-8

"""
    TGS API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 6.4.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.repository_rights import RepositoryRights  # noqa: E501
from swagger_client.rest import ApiException


class TestRepositoryRights(unittest.TestCase):
    """RepositoryRights unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRepositoryRights(self):
        """Test RepositoryRights"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.repository_rights.RepositoryRights()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
