# coding: utf-8

"""
    TGS API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 6.4.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.repository_api import RepositoryApi  # noqa: E501
from swagger_client.rest import ApiException


class TestRepositoryApi(unittest.TestCase):
    """RepositoryApi unit test stubs"""

    def setUp(self):
        self.api = api.repository_api.RepositoryApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_repository_controller_create(self):
        """Test case for repository_controller_create

        Begin cloning the repository if it doesn't exist.  # noqa: E501
        """
        pass

    def test_repository_controller_delete(self):
        """Test case for repository_controller_delete

        Delete the Tgstation.Server.Api.Models.Repository.  # noqa: E501
        """
        pass

    def test_repository_controller_read(self):
        """Test case for repository_controller_read

        Get Tgstation.Server.Api.Models.Repository status.  # noqa: E501
        """
        pass

    def test_repository_controller_update(self):
        """Test case for repository_controller_update

        Perform updats to the Tgstation.Server.Api.Models.Repository.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
