# coding: utf-8

"""
    TGS API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 6.4.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.user_api import UserApi  # noqa: E501
from swagger_client.rest import ApiException


class TestUserApi(unittest.TestCase):
    """UserApi unit test stubs"""

    def setUp(self):
        self.api = api.user_api.UserApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_user_controller_create(self):
        """Test case for user_controller_create

        Create a Tgstation.Server.Api.Models.User.  # noqa: E501
        """
        pass

    def test_user_controller_get_id(self):
        """Test case for user_controller_get_id

        Get a specific Tgstation.Server.Api.Models.User.  # noqa: E501
        """
        pass

    def test_user_controller_list(self):
        """Test case for user_controller_list

        List all Tgstation.Server.Api.Models.Users in the server.  # noqa: E501
        """
        pass

    def test_user_controller_read(self):
        """Test case for user_controller_read

        Get information about the current Tgstation.Server.Api.Models.User.  # noqa: E501
        """
        pass

    def test_user_controller_update(self):
        """Test case for user_controller_update

        Update a Tgstation.Server.Api.Models.User.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
