# coding: utf-8

"""
    TGS API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 6.4.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.configuration_api import ConfigurationApi  # noqa: E501
from swagger_client.rest import ApiException


class TestConfigurationApi(unittest.TestCase):
    """ConfigurationApi unit test stubs"""

    def setUp(self):
        self.api = api.configuration_api.ConfigurationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_configuration_controller_create(self):
        """Test case for configuration_controller_create

        Create a configuration directory.  # noqa: E501
        """
        pass

    def test_configuration_controller_delete(self):
        """Test case for configuration_controller_delete

        Deletes an empty directory  # noqa: E501
        """
        pass

    def test_configuration_controller_directory(self):
        """Test case for configuration_controller_directory

        Get the contents of a directory at a directoryPath  # noqa: E501
        """
        pass

    def test_configuration_controller_file(self):
        """Test case for configuration_controller_file

        Get the contents of a file at a filePath  # noqa: E501
        """
        pass

    def test_configuration_controller_list(self):
        """Test case for configuration_controller_list

        Get the contents of the root configuration directory.  # noqa: E501
        """
        pass

    def test_configuration_controller_update(self):
        """Test case for configuration_controller_update

        Write to a configuration file.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
