# coding: utf-8

"""
    TGS API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 6.4.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.chat_bot_rights import ChatBotRights  # noqa: E501
from swagger_client.rest import ApiException


class TestChatBotRights(unittest.TestCase):
    """ChatBotRights unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testChatBotRights(self):
        """Test ChatBotRights"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.chat_bot_rights.ChatBotRights()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
