# coding: utf-8

"""
    TGS API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 6.4.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.administration_api import AdministrationApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAdministrationApi(unittest.TestCase):
    """AdministrationApi unit test stubs"""

    def setUp(self):
        self.api = api.administration_api.AdministrationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_administration_controller_delete(self):
        """Test case for administration_controller_delete

        Attempts to restart the server.  # noqa: E501
        """
        pass

    def test_administration_controller_read(self):
        """Test case for administration_controller_read

        Get Tgstation.Server.Api.Models.Administration server information.  # noqa: E501
        """
        pass

    def test_administration_controller_update(self):
        """Test case for administration_controller_update

        Attempt to perform a server upgrade.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
