# coding: utf-8

"""
    TGS API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 6.4.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.dream_daemon import DreamDaemon  # noqa: E501
from swagger_client.rest import ApiException


class TestDreamDaemon(unittest.TestCase):
    """DreamDaemon unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDreamDaemon(self):
        """Test DreamDaemon"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.dream_daemon.DreamDaemon()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
