# coding: utf-8

"""
    TGS API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 6.4.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.instance_user_api import InstanceUserApi  # noqa: E501
from swagger_client.rest import ApiException


class TestInstanceUserApi(unittest.TestCase):
    """InstanceUserApi unit test stubs"""

    def setUp(self):
        self.api = api.instance_user_api.InstanceUserApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_instance_user_controller_create(self):
        """Test case for instance_user_controller_create

        Create am Tgstation.Server.Api.Models.InstanceUser.  # noqa: E501
        """
        pass

    def test_instance_user_controller_delete(self):
        """Test case for instance_user_controller_delete

        Delete an Tgstation.Server.Api.Models.InstanceUser.  # noqa: E501
        """
        pass

    def test_instance_user_controller_get_id(self):
        """Test case for instance_user_controller_get_id

        Gets a specific Tgstation.Server.Api.Models.InstanceUser.  # noqa: E501
        """
        pass

    def test_instance_user_controller_list(self):
        """Test case for instance_user_controller_list

        Lists Tgstation.Server.Api.Models.InstanceUsers for the instance.  # noqa: E501
        """
        pass

    def test_instance_user_controller_read(self):
        """Test case for instance_user_controller_read

        Read the active Tgstation.Server.Api.Models.InstanceUser.  # noqa: E501
        """
        pass

    def test_instance_user_controller_update(self):
        """Test case for instance_user_controller_update

        Update the permissions for an Tgstation.Server.Api.Models.InstanceUser.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
