# coding: utf-8

"""
    TGS API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 6.4.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class Administration(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'windows_host': 'bool',
        'tracked_repository_url': 'str',
        'latest_version': 'str',
        'new_version': 'str'
    }

    attribute_map = {
        'windows_host': 'windowsHost',
        'tracked_repository_url': 'trackedRepositoryUrl',
        'latest_version': 'latestVersion',
        'new_version': 'newVersion'
    }

    def __init__(self, windows_host=None, tracked_repository_url=None, latest_version=None, new_version=None):  # noqa: E501
        """Administration - a model defined in Swagger"""  # noqa: E501
        self._windows_host = None
        self._tracked_repository_url = None
        self._latest_version = None
        self._new_version = None
        self.discriminator = None
        if windows_host is not None:
            self.windows_host = windows_host
        if tracked_repository_url is not None:
            self.tracked_repository_url = tracked_repository_url
        if latest_version is not None:
            self.latest_version = latest_version
        if new_version is not None:
            self.new_version = new_version

    @property
    def windows_host(self):
        """Gets the windows_host of this Administration.  # noqa: E501

        If the server is running on a windows operating system  # noqa: E501

        :return: The windows_host of this Administration.  # noqa: E501
        :rtype: bool
        """
        return self._windows_host

    @windows_host.setter
    def windows_host(self, windows_host):
        """Sets the windows_host of this Administration.

        If the server is running on a windows operating system  # noqa: E501

        :param windows_host: The windows_host of this Administration.  # noqa: E501
        :type: bool
        """

        self._windows_host = windows_host

    @property
    def tracked_repository_url(self):
        """Gets the tracked_repository_url of this Administration.  # noqa: E501

        The GitHub repository the server is built to recieve updates from  # noqa: E501

        :return: The tracked_repository_url of this Administration.  # noqa: E501
        :rtype: str
        """
        return self._tracked_repository_url

    @tracked_repository_url.setter
    def tracked_repository_url(self, tracked_repository_url):
        """Sets the tracked_repository_url of this Administration.

        The GitHub repository the server is built to recieve updates from  # noqa: E501

        :param tracked_repository_url: The tracked_repository_url of this Administration.  # noqa: E501
        :type: str
        """

        self._tracked_repository_url = tracked_repository_url

    @property
    def latest_version(self):
        """Gets the latest_version of this Administration.  # noqa: E501

        The latest available version of the Tgstation.Server.Host assembly from the upstream repository. If System.Version.Major is higher than Tgstation.Server.Api.Models.Administration.NewVersion's the update cannot be applied due to API changes  # noqa: E501

        :return: The latest_version of this Administration.  # noqa: E501
        :rtype: str
        """
        return self._latest_version

    @latest_version.setter
    def latest_version(self, latest_version):
        """Sets the latest_version of this Administration.

        The latest available version of the Tgstation.Server.Host assembly from the upstream repository. If System.Version.Major is higher than Tgstation.Server.Api.Models.Administration.NewVersion's the update cannot be applied due to API changes  # noqa: E501

        :param latest_version: The latest_version of this Administration.  # noqa: E501
        :type: str
        """

        self._latest_version = latest_version

    @property
    def new_version(self):
        """Gets the new_version of this Administration.  # noqa: E501

        Changes the version of Tgstation.Server.Host to the given version from the upstream repository  # noqa: E501

        :return: The new_version of this Administration.  # noqa: E501
        :rtype: str
        """
        return self._new_version

    @new_version.setter
    def new_version(self, new_version):
        """Sets the new_version of this Administration.

        Changes the version of Tgstation.Server.Host to the given version from the upstream repository  # noqa: E501

        :param new_version: The new_version of this Administration.  # noqa: E501
        :type: str
        """

        self._new_version = new_version

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Administration, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Administration):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
