# coding: utf-8

"""
    TGS API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 6.4.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class DreamMaker(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'project_name': 'str',
        'api_validation_port': 'int',
        'api_validation_security_level': 'DreamDaemonSecurity'
    }

    attribute_map = {
        'project_name': 'projectName',
        'api_validation_port': 'apiValidationPort',
        'api_validation_security_level': 'apiValidationSecurityLevel'
    }

    def __init__(self, project_name=None, api_validation_port=None, api_validation_security_level=None):  # noqa: E501
        """DreamMaker - a model defined in Swagger"""  # noqa: E501
        self._project_name = None
        self._api_validation_port = None
        self._api_validation_security_level = None
        self.discriminator = None
        if project_name is not None:
            self.project_name = project_name
        if api_validation_port is not None:
            self.api_validation_port = api_validation_port
        if api_validation_security_level is not None:
            self.api_validation_security_level = api_validation_security_level

    @property
    def project_name(self):
        """Gets the project_name of this DreamMaker.  # noqa: E501

        The .dme file Tgstation.Server.Api.Models.DreamMaker tries to compile with without the extension  # noqa: E501

        :return: The project_name of this DreamMaker.  # noqa: E501
        :rtype: str
        """
        return self._project_name

    @project_name.setter
    def project_name(self, project_name):
        """Sets the project_name of this DreamMaker.

        The .dme file Tgstation.Server.Api.Models.DreamMaker tries to compile with without the extension  # noqa: E501

        :param project_name: The project_name of this DreamMaker.  # noqa: E501
        :type: str
        """

        self._project_name = project_name

    @property
    def api_validation_port(self):
        """Gets the api_validation_port of this DreamMaker.  # noqa: E501

        The port used during compilation to validate the DMAPI  # noqa: E501

        :return: The api_validation_port of this DreamMaker.  # noqa: E501
        :rtype: int
        """
        return self._api_validation_port

    @api_validation_port.setter
    def api_validation_port(self, api_validation_port):
        """Sets the api_validation_port of this DreamMaker.

        The port used during compilation to validate the DMAPI  # noqa: E501

        :param api_validation_port: The api_validation_port of this DreamMaker.  # noqa: E501
        :type: int
        """

        self._api_validation_port = api_validation_port

    @property
    def api_validation_security_level(self):
        """Gets the api_validation_security_level of this DreamMaker.  # noqa: E501


        :return: The api_validation_security_level of this DreamMaker.  # noqa: E501
        :rtype: DreamDaemonSecurity
        """
        return self._api_validation_security_level

    @api_validation_security_level.setter
    def api_validation_security_level(self, api_validation_security_level):
        """Sets the api_validation_security_level of this DreamMaker.


        :param api_validation_security_level: The api_validation_security_level of this DreamMaker.  # noqa: E501
        :type: DreamDaemonSecurity
        """

        self._api_validation_security_level = api_validation_security_level

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DreamMaker, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DreamMaker):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
