# coding: utf-8

"""
    TGS API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 6.4.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class DreamDaemon(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'active_compile_job': 'CompileJob',
        'staged_compile_job': 'CompileJob',
        'running': 'bool',
        'current_security': 'DreamDaemonSecurity',
        'current_port': 'int',
        'current_allow_webclient': 'bool',
        'soft_restart': 'bool',
        'soft_shutdown': 'bool',
        'auto_start': 'bool',
        'allow_web_client': 'bool',
        'security_level': 'DreamDaemonSecurity',
        'primary_port': 'int',
        'secondary_port': 'int',
        'startup_timeout': 'int',
        'heartbeat_seconds': 'int'
    }

    attribute_map = {
        'active_compile_job': 'activeCompileJob',
        'staged_compile_job': 'stagedCompileJob',
        'running': 'running',
        'current_security': 'currentSecurity',
        'current_port': 'currentPort',
        'current_allow_webclient': 'currentAllowWebclient',
        'soft_restart': 'softRestart',
        'soft_shutdown': 'softShutdown',
        'auto_start': 'autoStart',
        'allow_web_client': 'allowWebClient',
        'security_level': 'securityLevel',
        'primary_port': 'primaryPort',
        'secondary_port': 'secondaryPort',
        'startup_timeout': 'startupTimeout',
        'heartbeat_seconds': 'heartbeatSeconds'
    }

    def __init__(self, active_compile_job=None, staged_compile_job=None, running=None, current_security=None, current_port=None, current_allow_webclient=None, soft_restart=None, soft_shutdown=None, auto_start=None, allow_web_client=None, security_level=None, primary_port=None, secondary_port=None, startup_timeout=None, heartbeat_seconds=None):  # noqa: E501
        """DreamDaemon - a model defined in Swagger"""  # noqa: E501
        self._active_compile_job = None
        self._staged_compile_job = None
        self._running = None
        self._current_security = None
        self._current_port = None
        self._current_allow_webclient = None
        self._soft_restart = None
        self._soft_shutdown = None
        self._auto_start = None
        self._allow_web_client = None
        self._security_level = None
        self._primary_port = None
        self._secondary_port = None
        self._startup_timeout = None
        self._heartbeat_seconds = None
        self.discriminator = None
        if active_compile_job is not None:
            self.active_compile_job = active_compile_job
        if staged_compile_job is not None:
            self.staged_compile_job = staged_compile_job
        if running is not None:
            self.running = running
        if current_security is not None:
            self.current_security = current_security
        if current_port is not None:
            self.current_port = current_port
        if current_allow_webclient is not None:
            self.current_allow_webclient = current_allow_webclient
        if soft_restart is not None:
            self.soft_restart = soft_restart
        if soft_shutdown is not None:
            self.soft_shutdown = soft_shutdown
        if auto_start is not None:
            self.auto_start = auto_start
        if allow_web_client is not None:
            self.allow_web_client = allow_web_client
        if security_level is not None:
            self.security_level = security_level
        if primary_port is not None:
            self.primary_port = primary_port
        if secondary_port is not None:
            self.secondary_port = secondary_port
        if startup_timeout is not None:
            self.startup_timeout = startup_timeout
        if heartbeat_seconds is not None:
            self.heartbeat_seconds = heartbeat_seconds

    @property
    def active_compile_job(self):
        """Gets the active_compile_job of this DreamDaemon.  # noqa: E501


        :return: The active_compile_job of this DreamDaemon.  # noqa: E501
        :rtype: CompileJob
        """
        return self._active_compile_job

    @active_compile_job.setter
    def active_compile_job(self, active_compile_job):
        """Sets the active_compile_job of this DreamDaemon.


        :param active_compile_job: The active_compile_job of this DreamDaemon.  # noqa: E501
        :type: CompileJob
        """

        self._active_compile_job = active_compile_job

    @property
    def staged_compile_job(self):
        """Gets the staged_compile_job of this DreamDaemon.  # noqa: E501


        :return: The staged_compile_job of this DreamDaemon.  # noqa: E501
        :rtype: CompileJob
        """
        return self._staged_compile_job

    @staged_compile_job.setter
    def staged_compile_job(self, staged_compile_job):
        """Sets the staged_compile_job of this DreamDaemon.


        :param staged_compile_job: The staged_compile_job of this DreamDaemon.  # noqa: E501
        :type: CompileJob
        """

        self._staged_compile_job = staged_compile_job

    @property
    def running(self):
        """Gets the running of this DreamDaemon.  # noqa: E501

        The current status of Tgstation.Server.Api.Models.DreamDaemon  # noqa: E501

        :return: The running of this DreamDaemon.  # noqa: E501
        :rtype: bool
        """
        return self._running

    @running.setter
    def running(self, running):
        """Sets the running of this DreamDaemon.

        The current status of Tgstation.Server.Api.Models.DreamDaemon  # noqa: E501

        :param running: The running of this DreamDaemon.  # noqa: E501
        :type: bool
        """

        self._running = running

    @property
    def current_security(self):
        """Gets the current_security of this DreamDaemon.  # noqa: E501


        :return: The current_security of this DreamDaemon.  # noqa: E501
        :rtype: DreamDaemonSecurity
        """
        return self._current_security

    @current_security.setter
    def current_security(self, current_security):
        """Sets the current_security of this DreamDaemon.


        :param current_security: The current_security of this DreamDaemon.  # noqa: E501
        :type: DreamDaemonSecurity
        """

        self._current_security = current_security

    @property
    def current_port(self):
        """Gets the current_port of this DreamDaemon.  # noqa: E501

        The port the running Tgstation.Server.Api.Models.DreamDaemon instance is set to  # noqa: E501

        :return: The current_port of this DreamDaemon.  # noqa: E501
        :rtype: int
        """
        return self._current_port

    @current_port.setter
    def current_port(self, current_port):
        """Sets the current_port of this DreamDaemon.

        The port the running Tgstation.Server.Api.Models.DreamDaemon instance is set to  # noqa: E501

        :param current_port: The current_port of this DreamDaemon.  # noqa: E501
        :type: int
        """

        self._current_port = current_port

    @property
    def current_allow_webclient(self):
        """Gets the current_allow_webclient of this DreamDaemon.  # noqa: E501

        The webclient status the running Tgstation.Server.Api.Models.DreamDaemon instance is set to  # noqa: E501

        :return: The current_allow_webclient of this DreamDaemon.  # noqa: E501
        :rtype: bool
        """
        return self._current_allow_webclient

    @current_allow_webclient.setter
    def current_allow_webclient(self, current_allow_webclient):
        """Sets the current_allow_webclient of this DreamDaemon.

        The webclient status the running Tgstation.Server.Api.Models.DreamDaemon instance is set to  # noqa: E501

        :param current_allow_webclient: The current_allow_webclient of this DreamDaemon.  # noqa: E501
        :type: bool
        """

        self._current_allow_webclient = current_allow_webclient

    @property
    def soft_restart(self):
        """Gets the soft_restart of this DreamDaemon.  # noqa: E501

        If the server is undergoing a soft reset. This may be automatically set by changes to other fields  # noqa: E501

        :return: The soft_restart of this DreamDaemon.  # noqa: E501
        :rtype: bool
        """
        return self._soft_restart

    @soft_restart.setter
    def soft_restart(self, soft_restart):
        """Sets the soft_restart of this DreamDaemon.

        If the server is undergoing a soft reset. This may be automatically set by changes to other fields  # noqa: E501

        :param soft_restart: The soft_restart of this DreamDaemon.  # noqa: E501
        :type: bool
        """

        self._soft_restart = soft_restart

    @property
    def soft_shutdown(self):
        """Gets the soft_shutdown of this DreamDaemon.  # noqa: E501

        If the server is undergoing a soft shutdown  # noqa: E501

        :return: The soft_shutdown of this DreamDaemon.  # noqa: E501
        :rtype: bool
        """
        return self._soft_shutdown

    @soft_shutdown.setter
    def soft_shutdown(self, soft_shutdown):
        """Sets the soft_shutdown of this DreamDaemon.

        If the server is undergoing a soft shutdown  # noqa: E501

        :param soft_shutdown: The soft_shutdown of this DreamDaemon.  # noqa: E501
        :type: bool
        """

        self._soft_shutdown = soft_shutdown

    @property
    def auto_start(self):
        """Gets the auto_start of this DreamDaemon.  # noqa: E501

        If Tgstation.Server.Api.Models.DreamDaemon starts when it's Tgstation.Server.Api.Models.Instance starts  # noqa: E501

        :return: The auto_start of this DreamDaemon.  # noqa: E501
        :rtype: bool
        """
        return self._auto_start

    @auto_start.setter
    def auto_start(self, auto_start):
        """Sets the auto_start of this DreamDaemon.

        If Tgstation.Server.Api.Models.DreamDaemon starts when it's Tgstation.Server.Api.Models.Instance starts  # noqa: E501

        :param auto_start: The auto_start of this DreamDaemon.  # noqa: E501
        :type: bool
        """

        self._auto_start = auto_start

    @property
    def allow_web_client(self):
        """Gets the allow_web_client of this DreamDaemon.  # noqa: E501

        If the BYOND web client can be used to connect to the game server  # noqa: E501

        :return: The allow_web_client of this DreamDaemon.  # noqa: E501
        :rtype: bool
        """
        return self._allow_web_client

    @allow_web_client.setter
    def allow_web_client(self, allow_web_client):
        """Sets the allow_web_client of this DreamDaemon.

        If the BYOND web client can be used to connect to the game server  # noqa: E501

        :param allow_web_client: The allow_web_client of this DreamDaemon.  # noqa: E501
        :type: bool
        """

        self._allow_web_client = allow_web_client

    @property
    def security_level(self):
        """Gets the security_level of this DreamDaemon.  # noqa: E501


        :return: The security_level of this DreamDaemon.  # noqa: E501
        :rtype: DreamDaemonSecurity
        """
        return self._security_level

    @security_level.setter
    def security_level(self, security_level):
        """Sets the security_level of this DreamDaemon.


        :param security_level: The security_level of this DreamDaemon.  # noqa: E501
        :type: DreamDaemonSecurity
        """

        self._security_level = security_level

    @property
    def primary_port(self):
        """Gets the primary_port of this DreamDaemon.  # noqa: E501

        The first port Tgstation.Server.Api.Models.DreamDaemon uses. This should be the publically advertised port  # noqa: E501

        :return: The primary_port of this DreamDaemon.  # noqa: E501
        :rtype: int
        """
        return self._primary_port

    @primary_port.setter
    def primary_port(self, primary_port):
        """Sets the primary_port of this DreamDaemon.

        The first port Tgstation.Server.Api.Models.DreamDaemon uses. This should be the publically advertised port  # noqa: E501

        :param primary_port: The primary_port of this DreamDaemon.  # noqa: E501
        :type: int
        """

        self._primary_port = primary_port

    @property
    def secondary_port(self):
        """Gets the secondary_port of this DreamDaemon.  # noqa: E501

        The second port Tgstation.Server.Api.Models.DreamDaemon uses  # noqa: E501

        :return: The secondary_port of this DreamDaemon.  # noqa: E501
        :rtype: int
        """
        return self._secondary_port

    @secondary_port.setter
    def secondary_port(self, secondary_port):
        """Sets the secondary_port of this DreamDaemon.

        The second port Tgstation.Server.Api.Models.DreamDaemon uses  # noqa: E501

        :param secondary_port: The secondary_port of this DreamDaemon.  # noqa: E501
        :type: int
        """

        self._secondary_port = secondary_port

    @property
    def startup_timeout(self):
        """Gets the startup_timeout of this DreamDaemon.  # noqa: E501

        The DreamDaemon startup timeout in seconds  # noqa: E501

        :return: The startup_timeout of this DreamDaemon.  # noqa: E501
        :rtype: int
        """
        return self._startup_timeout

    @startup_timeout.setter
    def startup_timeout(self, startup_timeout):
        """Sets the startup_timeout of this DreamDaemon.

        The DreamDaemon startup timeout in seconds  # noqa: E501

        :param startup_timeout: The startup_timeout of this DreamDaemon.  # noqa: E501
        :type: int
        """

        self._startup_timeout = startup_timeout

    @property
    def heartbeat_seconds(self):
        """Gets the heartbeat_seconds of this DreamDaemon.  # noqa: E501

        The number of seconds between each watchdog heartbeat. 0 disables.  # noqa: E501

        :return: The heartbeat_seconds of this DreamDaemon.  # noqa: E501
        :rtype: int
        """
        return self._heartbeat_seconds

    @heartbeat_seconds.setter
    def heartbeat_seconds(self, heartbeat_seconds):
        """Sets the heartbeat_seconds of this DreamDaemon.

        The number of seconds between each watchdog heartbeat. 0 disables.  # noqa: E501

        :param heartbeat_seconds: The heartbeat_seconds of this DreamDaemon.  # noqa: E501
        :type: int
        """

        self._heartbeat_seconds = heartbeat_seconds

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DreamDaemon, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DreamDaemon):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
