# coding: utf-8

"""
    TGS API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 6.4.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class Instance(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'name': 'str',
        'path': 'str',
        'online': 'bool',
        'configuration_type': 'ConfigurationType',
        'auto_update_interval': 'int',
        'chat_bot_limit': 'int',
        'move_job': 'Job'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'path': 'path',
        'online': 'online',
        'configuration_type': 'configurationType',
        'auto_update_interval': 'autoUpdateInterval',
        'chat_bot_limit': 'chatBotLimit',
        'move_job': 'moveJob'
    }

    def __init__(self, id=None, name=None, path=None, online=None, configuration_type=None, auto_update_interval=None, chat_bot_limit=None, move_job=None):  # noqa: E501
        """Instance - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._name = None
        self._path = None
        self._online = None
        self._configuration_type = None
        self._auto_update_interval = None
        self._chat_bot_limit = None
        self._move_job = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if path is not None:
            self.path = path
        if online is not None:
            self.online = online
        if configuration_type is not None:
            self.configuration_type = configuration_type
        if auto_update_interval is not None:
            self.auto_update_interval = auto_update_interval
        if chat_bot_limit is not None:
            self.chat_bot_limit = chat_bot_limit
        if move_job is not None:
            self.move_job = move_job

    @property
    def id(self):
        """Gets the id of this Instance.  # noqa: E501

        The id of the Tgstation.Server.Api.Models.Instance. Not modifiable  # noqa: E501

        :return: The id of this Instance.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Instance.

        The id of the Tgstation.Server.Api.Models.Instance. Not modifiable  # noqa: E501

        :param id: The id of this Instance.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this Instance.  # noqa: E501

        The name of the Tgstation.Server.Api.Models.Instance  # noqa: E501

        :return: The name of this Instance.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Instance.

        The name of the Tgstation.Server.Api.Models.Instance  # noqa: E501

        :param name: The name of this Instance.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def path(self):
        """Gets the path of this Instance.  # noqa: E501

        The path to where the Tgstation.Server.Api.Models.Instance is located. Can only be changed while the Tgstation.Server.Api.Models.Instance is offline. Must not exist when the instance is created  # noqa: E501

        :return: The path of this Instance.  # noqa: E501
        :rtype: str
        """
        return self._path

    @path.setter
    def path(self, path):
        """Sets the path of this Instance.

        The path to where the Tgstation.Server.Api.Models.Instance is located. Can only be changed while the Tgstation.Server.Api.Models.Instance is offline. Must not exist when the instance is created  # noqa: E501

        :param path: The path of this Instance.  # noqa: E501
        :type: str
        """

        self._path = path

    @property
    def online(self):
        """Gets the online of this Instance.  # noqa: E501

        If the Tgstation.Server.Api.Models.Instance is online  # noqa: E501

        :return: The online of this Instance.  # noqa: E501
        :rtype: bool
        """
        return self._online

    @online.setter
    def online(self, online):
        """Sets the online of this Instance.

        If the Tgstation.Server.Api.Models.Instance is online  # noqa: E501

        :param online: The online of this Instance.  # noqa: E501
        :type: bool
        """

        self._online = online

    @property
    def configuration_type(self):
        """Gets the configuration_type of this Instance.  # noqa: E501


        :return: The configuration_type of this Instance.  # noqa: E501
        :rtype: ConfigurationType
        """
        return self._configuration_type

    @configuration_type.setter
    def configuration_type(self, configuration_type):
        """Sets the configuration_type of this Instance.


        :param configuration_type: The configuration_type of this Instance.  # noqa: E501
        :type: ConfigurationType
        """

        self._configuration_type = configuration_type

    @property
    def auto_update_interval(self):
        """Gets the auto_update_interval of this Instance.  # noqa: E501

        The time interval in minutes the repository is automatically pulled and compiles. 0 disables  # noqa: E501

        :return: The auto_update_interval of this Instance.  # noqa: E501
        :rtype: int
        """
        return self._auto_update_interval

    @auto_update_interval.setter
    def auto_update_interval(self, auto_update_interval):
        """Sets the auto_update_interval of this Instance.

        The time interval in minutes the repository is automatically pulled and compiles. 0 disables  # noqa: E501

        :param auto_update_interval: The auto_update_interval of this Instance.  # noqa: E501
        :type: int
        """

        self._auto_update_interval = auto_update_interval

    @property
    def chat_bot_limit(self):
        """Gets the chat_bot_limit of this Instance.  # noqa: E501

        The maximum number of Tgstation.Server.Api.Models.ChatBots the Tgstation.Server.Api.Models.Instance may contain.  # noqa: E501

        :return: The chat_bot_limit of this Instance.  # noqa: E501
        :rtype: int
        """
        return self._chat_bot_limit

    @chat_bot_limit.setter
    def chat_bot_limit(self, chat_bot_limit):
        """Sets the chat_bot_limit of this Instance.

        The maximum number of Tgstation.Server.Api.Models.ChatBots the Tgstation.Server.Api.Models.Instance may contain.  # noqa: E501

        :param chat_bot_limit: The chat_bot_limit of this Instance.  # noqa: E501
        :type: int
        """

        self._chat_bot_limit = chat_bot_limit

    @property
    def move_job(self):
        """Gets the move_job of this Instance.  # noqa: E501


        :return: The move_job of this Instance.  # noqa: E501
        :rtype: Job
        """
        return self._move_job

    @move_job.setter
    def move_job(self, move_job):
        """Sets the move_job of this Instance.


        :param move_job: The move_job of this Instance.  # noqa: E501
        :type: Job
        """

        self._move_job = move_job

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Instance, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Instance):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
